spring:
  application:
    name: sob-blog
  datasource:
    url: jdbc:mysql://106.14.20.146:3307/kblog_system?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
  redis:
    port: 6379
    host: 192.168.146.132
    password: 123456
server:
  port: 2021
