spring:
  application:
    name: k-blog
  datasource:
    url: jdbc:mysql://127.0.0.1/kblog_system?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
  redis:
    port: 6379
    host: 127.0.0.1
#    password: 123456
server:
  port: 2021
k.blog.image.save-path: E:\Code\J2EE\images
# 2MB
k.blog.image.max-size: 2097152